# Generated by Django 6.0.4 on 2026-05-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_custom_objects', '0014_fix_mixed_case_field_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='customobjecttype',
            name='show_dedicated_tab',
            field=models.BooleanField(default=False),
        ),
    ]
